server:
  AppMode: debug  # release
  JwtKey: shinanguatouya777
  port: 9090
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: logistics-go
  username: root
  password: wangt777
  charset: utf8
  loc: Asia/Shanghai
