server:
  AppMode: debug  # release
  JwtKey: shinanguatouya777
  port: 9090
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: logistics-go
  username: root
  password: 1234
  charset: utf8
  loc: Asia/Shanghai
logistics:
  SF:
    url: https://fapi.sf-express.com/fopApiServices/access/sandbox/enter
    key: XXXX
    partnerID: XXXX
