definitions:
  schemas.AddLogisticsResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.Order'
        description: 物流信息
      message:
        description: 响应信息
        example: success
        type: string
      status:
        description: 响应状态
        example: 200
        type: integer
    type: object
  schemas.CargoList:
    properties:
      count:
        description: 数量
        example: 5
        type: integer
      height:
        description: 高(单位默认为厘米)
        example: 80
        type: number
      length:
        description: 长(单位默认为厘米)
        example: 100
        type: number
      name:
        description: 货物名称
        example: 货物名称
        type: string
      uint:
        description: 单位， 如个、台、件
        example: 件
        type: string
      volume:
        description: 宽(单位默认为厘米)
        example: 480000
        type: number
      weight:
        description: 重量(单位:kg)
        example: 60
        type: number
      width:
        description: 宽(单位默认为厘米)
        example: 60
        type: number
    type: object
  schemas.GetUserInfoResponse:
    properties:
      data:
        description: 用户信息
        items:
          $ref: '#/definitions/schemas.UserInfoData'
        type: array
      message:
        description: 响应信息
        example: 成功
        type: string
      status:
        description: 响应状态
        example: 200
        type: integer
      total:
        description: 用户数量
        example: 1
        type: integer
    type: object
  schemas.LoginRequest:
    properties:
      password:
        description: 密码
        example: '****'
        maxLength: 120
        minLength: 6
        type: string
      username:
        description: 用户名
        example: name
        maxLength: 12
        minLength: 4
        type: string
    required:
    - password
    - username
    type: object
  schemas.LoginResponse:
    properties:
      message:
        description: |-
          Id      uint   `json:"id" form:"id" example:"1"`             //用户id
          Name    string `json:"name" form:"name" example:"string"`    //用户名
        example: 成功
        type: string
      status:
        description: 响应状态
        example: 200
        type: integer
      token:
        description: 令牌
        example: asdffgh
        type: string
    type: object
  schemas.Logistics:
    properties:
      barcode:
        description: 运单号
        type: string
      carrier_code:
        description: 物流公司代码
        type: string
      id:
        description: 订单号
        type: string
      trackInfo:
        description: 物流时效
        items:
          $ref: '#/definitions/schemas.TrackInfo'
        type: array
      weblink:
        description: 物流官网
        type: string
    type: object
  schemas.LogisticsRequest:
    properties:
      cargoList:
        $ref: '#/definitions/schemas.CargoList'
        description: 货物明细
      delivery_address:
        description: 到件方详细地址
        example: 沙头街道皇庭广场
        type: string
      delivery_city:
        description: 到件方所在地级行政区名称
        example: 深圳市
        type: string
      delivery_contact:
        description: 到件方联系人
        example: 李华
        type: string
      delivery_county:
        description: 到件方所在县/区级行政区名称
        example: 福田区
        type: string
      delivery_province:
        description: 到件方所在省级行政区名称
        example: 广东省
        type: string
      delivery_tel:
        description: 到件方联系电话
        example: "18452154695"
        type: string
      expected_pick_up_time:
        description: 希望上门取件时间。格式：yyyy-MM-dd HH:mm:ss。isDocall=1时有效，其中，预约时间超过晚8点，会自动约成第二天。
        example: "2022-05-21 00:00:00"
        type: string
      is_do_call:
        description: 是否需要上门,0-不下call，不会通知小哥上门；1-下call，默认2小时内上门
        example: 1
        type: integer
      pay_method:
        description: 付款方式(邮费)：1.寄方付2.收方付3.第三方付
        example: 1
        type: integer
      remark:
        example: 备注
        type: string
      send_address:
        description: 寄件方详细地址
        example: 粤海街道科兴科学园
        type: string
      send_city:
        description: 寄件方所在地级行政区名称
        example: 深圳市
        type: string
      send_contact:
        description: 寄件方联系人
        example: 张湘
        type: string
      send_county:
        description: 寄件人所在县/区级行政区名称
        example: 南山区
        type: string
      send_province:
        description: 寄件方所在省级行政区名称
        example: 广东省
        type: string
      send_tel:
        description: 寄件方联系电话
        example: "18452154695"
        type: string
    type: object
  schemas.Order:
    properties:
      barcode:
        description: 运单号
        type: string
      carrier_code:
        description: 物流公司代码
        type: string
      weblink:
        description: 物流官网
        type: string
    type: object
  schemas.PasswordData:
    properties:
      password:
        description: 密码
        example: '****'
        maxLength: 120
        minLength: 6
        type: string
    required:
    - password
    type: object
  schemas.PickUp:
    properties:
      address:
        example: 广东省深圳市福田区沙尾街道金地三路888号
        type: string
      id:
        example: "12345678"
        type: string
      status:
        example: 0
        type: integer
    type: object
  schemas.PickUpRequest:
    properties:
      address:
        example: 广东省深圳市福田区沙尾街道金地三路888号
        type: string
      status:
        enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        example: 0
        type: integer
    type: object
  schemas.PickUpResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.PickUp'
        description: 物流信息
      message:
        description: 响应信息
        example: success
        type: string
      status:
        description: 响应状态
        example: 200
        type: integer
    type: object
  schemas.RegularResponse:
    properties:
      message:
        description: 响应信息
        example: 成功
        type: string
      status:
        description: 响应状态
        example: 200
        type: integer
    type: object
  schemas.SearchLogisticsResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.Logistics'
        description: 物流信息
      message:
        description: 响应信息
        example: success
        type: string
      status:
        description: 响应状态
        example: 200
        type: integer
    type: object
  schemas.TrackInfo:
    properties:
      date:
        description: 时间
        type: string
      status_description:
        description: 物流描述
        type: string
    type: object
  schemas.UserInfoData:
    properties:
      role:
        description: 角色码
        example: 1
        type: integer
      username:
        description: 用户名
        example: name
        type: string
    type: object
  schemas.UserRegistered:
    properties:
      password:
        description: 密码
        example: '****'
        maxLength: 120
        minLength: 6
        type: string
      role:
        description: 角色码
        example: 2
        minimum: 2
        type: integer
      username:
        description: 用户名
        example: name
        maxLength: 12
        minLength: 4
        type: string
    required:
    - password
    - role
    - username
    type: object
info:
  contact:
    email: pimpkin_mak@163.com
    name: Mzihao
  description: 聚合物流服务
  title: Logistics Open Api
  version: "1.0"
paths:
  /api/healthcheck:
    get:
      consumes:
      - application/json
      description: 健康检测
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.RegularResponse'
      summary: 健康检测
      tags:
      - 健康检测模块
  /api/v1/admin/changePassword/{id}:
    put:
      consumes:
      - application/json
      description: 修改密码
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      - description: 请求参数data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schemas.PasswordData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.RegularResponse'
      security:
      - ApiKeyAuth: []
      summary: 修改密码
      tags:
      - 用户
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: 后台登陆
      parameters:
      - description: 请求参数data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schemas.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.LoginResponse'
      summary: 后台登陆
      tags:
      - 登录控制模块
  /api/v1/logistics/{barcode}:
    get:
      consumes:
      - application/json
      description: 物流查询
      parameters:
      - description: 物流单号
        in: path
        name: barcode
        required: true
        type: string
      - description: 物流公司代码
        in: query
        name: carrierCode
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.SearchLogisticsResponse'
      security:
      - ApiKeyAuth: []
      summary: 物流查询
      tags:
      - 物流
  /api/v1/logistics/{carrierCode}:
    post:
      consumes:
      - application/json
      description: 物流下单
      parameters:
      - description: 物流商代码
        in: path
        name: carrierCode
        required: true
        type: string
      - description: 请求参数data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schemas.LogisticsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.AddLogisticsResponse'
      security:
      - ApiKeyAuth: []
      summary: 物流下单
      tags:
      - 物流
  /api/v1/pickUp:
    post:
      consumes:
      - application/json
      description: 自提物流下单
      parameters:
      - description: 请求参数data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schemas.PickUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.PickUpResponse'
      security:
      - ApiKeyAuth: []
      summary: 自提物流下单
      tags:
      - 自提物流
  /api/v1/pickUp/{id}:
    delete:
      consumes:
      - application/json
      description: 自提物流取消订单
      parameters:
      - description: 物流单号
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.PickUpResponse'
      security:
      - ApiKeyAuth: []
      summary: 自提物流取消订单
      tags:
      - 自提物流
    get:
      consumes:
      - application/json
      description: 自提物流查询
      parameters:
      - description: 物流单号
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.PickUpResponse'
      security:
      - ApiKeyAuth: []
      summary: 自提物流查询
      tags:
      - 自提物流
    put:
      consumes:
      - application/json
      description: 自提物流信息修改
      parameters:
      - description: 物流单号
        in: path
        name: id
        required: true
        type: string
      - description: 请求参数data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schemas.PickUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.PickUpResponse'
      security:
      - ApiKeyAuth: []
      summary: 自提物流信息修改
      tags:
      - 自提物流
  /api/v1/user/{id}:
    delete:
      consumes:
      - application/json
      description: 删除用户
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.RegularResponse'
      security:
      - ApiKeyAuth: []
      summary: 删除用户
      tags:
      - 用户
    get:
      consumes:
      - application/json
      description: 查询单个用户
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.GetUserInfoResponse'
      security:
      - ApiKeyAuth: []
      summary: 查询单个用户
      tags:
      - 用户
    put:
      consumes:
      - application/json
      description: 编辑用户
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      - description: 请求参数data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schemas.UserInfoData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.RegularResponse'
      security:
      - ApiKeyAuth: []
      summary: 编辑用户
      tags:
      - 用户
  /api/v1/user/add:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 请求参数data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schemas.UserRegistered'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.RegularResponse'
      summary: 用户注册
      tags:
      - 用户
  /api/v1/users:
    get:
      consumes:
      - application/json
      description: 查询用户列表
      parameters:
      - description: 用户名
        in: query
        name: username
        type: string
      - description: 页面容量
        in: query
        name: page_size
        type: string
      - description: 页数
        in: query
        name: page_num
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.GetUserInfoResponse'
      security:
      - ApiKeyAuth: []
      summary: 查询用户列表
      tags:
      - 用户
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
